apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
       spec:
         containers:
           - name: busybox
             image: busybox:latest
         command: ["/bin/sh", "-c", {{ .Values.command }}]
         restartPolicy: OnFailure
