apiVersion: v2
name: devpro-samples-wordpress
description: Helm chart sample for Wordpress
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  # https://github.com/bitnami/charts/tree/master/bitnami/wordpress/
  - name: wordpress
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
